In [2]:
import numpy as np

# Different ways to create numpy array

## Using list :; type 1

In [3]:
l = [0,1,2,3,4,5,6,7]
arr = np.array(l)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

## Using list :: type 2

In [5]:
m  = [[1,2,3],[4,5,6],[7,8,9]]
marr = np.array(m)
marr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Using np.arange function :: type 1

In [7]:
l1  = np.arange(20)
l1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Using np.arange and reshape function :: type 2

In [8]:
l2 = l1.reshape(4,5)
print(l2.shape)
l2

(4, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Using Reshape with other vector generator function

In [9]:
l4 = np.linspace(0,30,4)
l4

array([ 0., 10., 20., 30.])

In [10]:
l5 = np.logspace(0,3,5)
l5

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

## Using np.random.rand and np.random.randn functions

In [11]:
l6 = np.random.rand(2,3)
l6

array([[0.93476345, 0.99487097, 0.08863499],
       [0.31980326, 0.64634302, 0.25319064]])

In [27]:
l7 = np.random.randn(4,5) * 100
l7

array([[  -7.24758161,  -54.09956602,  107.37886912, -106.89979764,
          99.12482563],
       [ 315.08435939,  205.45031289,  -46.33966764,  -10.07733139,
          60.02003072],
       [-146.88768318, -156.11916634, -104.30263335,   22.28484248,
         -66.76469011],
       [ 104.02876492,  -16.06344075, -149.21033881,   98.20307737,
         -61.70289509]])

In [24]:
l7.shape

(4, 5)

In [26]:
l8 = np.random.randint(2,19,5)
l8

array([11, 12,  3,  4,  7])

In [36]:
l9 = np.ones(6)
l9

array([1., 1., 1., 1., 1., 1.])

In [37]:
l10 = np.zeros(7)
l10

array([0., 0., 0., 0., 0., 0., 0.])

In [40]:
l11 = np.eye(5)
l11

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
l12 =np.eye(4)
l12

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
l13 = np.zeros((3,4))
l13

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
l14 = np.ones((4,3))
l14

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])